name: Update README Problem Count

on:
  push:
    paths:
      - '**.java'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # 👈 Allows manual trigger from GitHub UI

permissions:
  contents: write  # 👈 This gives the workflow permission to push to the repo

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Count LeetCode solutions
        run: |
          EASY=$(find Easy -name '*.java' | wc -l || echo 0)
          MEDIUM=$(find Medium -name '*.java' | wc -l || echo 0)
          HARD=$(find Hard -name '*.java' | wc -l || echo 0)
          echo "EASY=$EASY" >> $GITHUB_ENV
          echo "MEDIUM=$MEDIUM" >> $GITHUB_ENV
          echo "HARD=$HARD" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i -E "s/(\| 🟢 Easy\s+\|\s+)[0-9]+(\s+\|)/\1$EASY\2/" README.md
          sed -i -E "s/(\| 🟡 Medium\s+\|\s+)[0-9]+(\s+\|)/\1$MEDIUM\2/" README.md
          sed -i -E "s/(\| 🔴 Hard\s+\|\s+)[0-9]+(\s+\|)/\1$HARD\2/" README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "📊 Updated problem counts" || echo "No changes to commit"
          git pull --rebase
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$(echo ${{ github.ref }} | cut -d'/' -f3)
