name: Update README Problem Count

on:
  push:
    paths:
      - '**.java'
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Count LeetCode solutions
        run: |
          EASY=$(find Easy -name '*.java' | wc -l || echo 0)
          MEDIUM=$(find Medium -name '*.java' | wc -l || echo 0)
          HARD=$(find Hard -name '*.java' | wc -l || echo 0)

          echo "EASY=$EASY" >> $GITHUB_ENV
          echo "MEDIUM=$MEDIUM" >> $GITHUB_ENV
          echo "HARD=$HARD" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i '/| 游릭 Easy     |/c\| 游릭 Easy     | '"$EASY"'               |' README.md
          sed -i '/| 游리 Medium   |/c\| 游리 Medium   | '"$MEDIUM"'               |' README.md
          sed -i '/| 游댮 Hard     |/c\| 游댮 Hard     | '"$HARD"'               |' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "游늵 Updated problem counts" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$(echo ${{ github.ref }} | cut -d'/' -f3)
